"""Remove unique constraint

Revision ID: ef2e673b263d
Revises: a8431237e25a
Create Date: 2025-12-11 11:12:05.186763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2e673b263d'
down_revision: Union[str, Sequence[str], None] = 'a8431237e25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'industry_aggregations_new',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('industry', sa.String, nullable=False),  # remove unique=True
        sa.Column('avg_pe_ratio', sa.Float),
        sa.Column('avg_revenue_growth', sa.Float),
        sa.Column('total_revenue', sa.Float),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    # copy data
    op.execute("""
        INSERT INTO industry_aggregations_new (id, industry, avg_pe_ratio, avg_revenue_growth, total_revenue, created_at)
        SELECT id, industry, avg_pe_ratio, avg_revenue_growth, total_revenue, created_at
        FROM industry_aggregations
    """)
    # drop old table
    op.drop_table('industry_aggregations')
    # rename
    op.rename_table('industry_aggregations_new', 'industry_aggregations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'industry_aggregations_old',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('industry', sa.String, nullable=False, unique=True),  # wieder UNIQUE
        sa.Column('avg_pe_ratio', sa.Float),
        sa.Column('avg_revenue_growth', sa.Float),
        sa.Column('total_revenue', sa.Float),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
   
    op.execute("""
        INSERT INTO industry_aggregations_old (id, industry, avg_pe_ratio, avg_revenue_growth, total_revenue, created_at)
        SELECT id, industry, avg_pe_ratio, avg_revenue_growth, total_revenue, created_at
        FROM industry_aggregations
        GROUP BY industry
    """)
    
    op.drop_table('industry_aggregations')
    
    op.rename_table('industry_aggregations_old', 'industry_aggregations')
    # ### end Alembic commands ###
